export const ADMIN_ROUTE = '/admin'
export const POST_ROUTE = '/post'
export const REGISTRATION_ROUTE = '/registration'
export const LOGIN_ROUTE = '/login'
export const ORGANIZATION_ROUTE = '/organization'
